name: pin_lock

version: 0.1.0

description: "A full solution to local authentication: it contains authentication logic and tracks authentication-relevant data, while providing an interface for app-specific UI implementatin."

repository: https://github.com/DutchCodingCompany/pin_lock

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  parameterized_test: ^1.1.3
  very_good_analysis: ^5.1.0


flutter:
  plugin:
    platforms:
      android:
        package: nl.dutchcodingcompany.pin_lock
        pluginClass: PinLockPlugin
      ios:
        pluginClass: PinLockPlugin
